### ISSUE TITLE
behavior rolled out of new relic?

### ISSUE THREAD

**Issue by ashanbrown** [Genius/heroku-true-relic#5]
I know this is deprecated and all that but I wanted to check with you all if you can still get this data from new relic.  I can't find the graphs with "Request Queueing" graphs on new relic anymore.  I couldn't quite remember what they looked like but I found them in your post:

http://genius.com/1506508/James-somers-herokus-ugly-secret/Update-2-15-heres-how-to-modify-your-application-to-make-new-relic-report-dyno-level-queue-time

I'm chatting with tech support at new relic but they said the graphs have changed a bit.  Assuming you all still even use new relic, do you happen to know what might have happened to them?  I don't want to be a conspiracy theorist but... ;)

Thanks, Andrew

**Comment by a-warner** [comment]
Weird! I still have the request queuing section on my graphs in new relic.

**Comment by ashanbrown** [comment]
Nevermind, I did find the graphs.  I realize that my default display was the histogram, which doesn't show the request queueing.  Not sure why tech support wasn't able to point me in the right direction.
